install.packages("sp")
install.packages("maptools")
install.packages("rgeos")
install.packages("ggmap")
library("sp")
library("maptools")
library("rgeos")
library("ggmap")
bmp.map <- get_map("Washington, DC", zoom = 12)
ggmap(bmp.map)
ggmap(bmp.map) + geom_point(data = BMP, aes(BMP$LONGITUDE, BMP$LATITUDE), size = 1)
src.map <- get_map("Washington, DC", zoom = 12)
ggmap(src.map)
SRC <- subset(BMP, BMP$SRC_GENERATION == "Yes")
ggmap(src.map) + geom_point(data = SRC, aes(SRC$LONGITUDE, SRC$LATITUDE), size = 1)
rs.map <- get_map("Washington, DC", zoom = 12)
ggmap(rs.map)
RS<- subset(BMP, BMP$RIVERSMART_REWARDS == "Yes")
ggmap(rs.map) + geom_point(data = RS, aes(RS$LONGITUDE, RS$LATITUDE), size = 1)
